

TSINGHUA_BREEDS = [
    "Affenpinscher",
    "Afghan Hound",
    "African Hunting Dog",
    "Airedale",
    "American Staffordshire Terrier",
    "Appenzeller",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset",
    "Beagle",
    "Bedlington Terrier",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black-and-tan Coonhound",
    "Black Sable",
    "Blenheim Spaniel",
    "Bloodhound",
    "Bluetick",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Bull",
    "Bouvier Des Flandres",
    "Boxer",
    "Brabancon Griffon",
    "Briard",
    "Brittany Spaniel",
    "Bull Mastiff",
    "Cairn",
    "Cane Carso",
    "Cardigan",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested Dog",
    "Chow",
    "Clumber",
    "Cocker Spaniel",
    "Collie",
    "Curly-coated Retriever",
    "Dandie Dinmont",
    "Dhole",
    "Dingo",
    "Doberman",
    "English Foxhound",
    "English Setter",
    "English Springer",
    "Entlebucher",
    "Eskimo Dog",
    "Fila braziliero",
    "Flat-coated Retriever",
    "French Bulldog",
    "German Shepherd",
    "German Short-haired Pointer",
    "Giant Schnauzer",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Groenendael",
    "Ibizan Hound",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Japanese Spaniel",
    "Japanese Spitzes",
    "Keeshond",
    "Kelpie",
    "Kerry Blue Terrier",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lakeland Terrier",
    "Leonberg",
    "Lhasa",
    "Malamute",
    "Malinois",
    "Maltese Dog",
    "Mexican Hairless",
    "Miniature Pinscher",
    "Miniature Poodle",
    "Miniature Schnauzer",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Pekinese",
    "Pembroke",
    "Pomeranian",
    "Pug",
    "Redbone",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Scotch Terrier",
    "Scottish Deerhound",
    "Sealyham Terrier",
    "Shetland Sheepdog",
    "Shiba",
    "Shih-Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Soft-coated Wheaten Terrier",
    "Staffordshire Bullterrier",
    "Standard Poodle",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Tibetan Mastiff",
    "Tibetan Terrier",
    "Toy Poodle",
    "Toy Terrier",
    "Vizsla",
    "Walker Hound",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "West Highland White Terrier",
    "Whippet",
    "Wire-haired Fox Terrier",
    "Yorkshire Terrier",
]
